services:
  web:
    build: .
    ports:
    - 127.0.0.1:3000:80
    volumes:
      - ./data:/app/data
  tasks:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
    command: ["uv", "run", "tasks.py"]